################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
SYS/CYC_SYS_ADC.obj: ../SYS/CYC_SYS_ADC.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"c:/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --preinclude="C:/ti/ccsv6/ccs_base/msp430/include/msp430f5xx_6xxgeneric.h" --include_path="c:/ti/ccsv6/ccs_base/msp430/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/Common" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/SPP_drv/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/BLE_drv/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/SYS" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/SPP_drv/example app" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/BLE_drv/example app" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/SYS/MSP430Ware" --include_path="c:/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --advice:power=all -g --relaxed_ansi --define=__MSP430F5328__ --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="SYS/CYC_SYS_ADC.pp" --obj_directory="SYS" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SYS/CYC_SYS_Clock.obj: ../SYS/CYC_SYS_Clock.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"c:/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --preinclude="C:/ti/ccsv6/ccs_base/msp430/include/msp430f5xx_6xxgeneric.h" --include_path="c:/ti/ccsv6/ccs_base/msp430/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/Common" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/SPP_drv/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/BLE_drv/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/SYS" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/SPP_drv/example app" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/BLE_drv/example app" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/SYS/MSP430Ware" --include_path="c:/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --advice:power=all -g --relaxed_ansi --define=__MSP430F5328__ --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="SYS/CYC_SYS_Clock.pp" --obj_directory="SYS" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SYS/CYC_SYS_GPIO.obj: ../SYS/CYC_SYS_GPIO.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"c:/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --preinclude="C:/ti/ccsv6/ccs_base/msp430/include/msp430f5xx_6xxgeneric.h" --include_path="c:/ti/ccsv6/ccs_base/msp430/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/Common" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/SPP_drv/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/BLE_drv/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/SYS" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/SPP_drv/example app" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/BLE_drv/example app" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/SYS/MSP430Ware" --include_path="c:/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --advice:power=all -g --relaxed_ansi --define=__MSP430F5328__ --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="SYS/CYC_SYS_GPIO.pp" --obj_directory="SYS" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SYS/CYC_SYS_I2C.obj: ../SYS/CYC_SYS_I2C.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"c:/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --preinclude="C:/ti/ccsv6/ccs_base/msp430/include/msp430f5xx_6xxgeneric.h" --include_path="c:/ti/ccsv6/ccs_base/msp430/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/Common" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/SPP_drv/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/BLE_drv/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/SYS" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/SPP_drv/example app" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/BLE_drv/example app" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/SYS/MSP430Ware" --include_path="c:/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --advice:power=all -g --relaxed_ansi --define=__MSP430F5328__ --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="SYS/CYC_SYS_I2C.pp" --obj_directory="SYS" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SYS/CYC_SYS_Init.obj: ../SYS/CYC_SYS_Init.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"c:/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --preinclude="C:/ti/ccsv6/ccs_base/msp430/include/msp430f5xx_6xxgeneric.h" --include_path="c:/ti/ccsv6/ccs_base/msp430/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/Common" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/SPP_drv/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/BLE_drv/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/SYS" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/SPP_drv/example app" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/BLE_drv/example app" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/SYS/MSP430Ware" --include_path="c:/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --advice:power=all -g --relaxed_ansi --define=__MSP430F5328__ --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="SYS/CYC_SYS_Init.pp" --obj_directory="SYS" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SYS/CYC_SYS_PWM.obj: ../SYS/CYC_SYS_PWM.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"c:/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --preinclude="C:/ti/ccsv6/ccs_base/msp430/include/msp430f5xx_6xxgeneric.h" --include_path="c:/ti/ccsv6/ccs_base/msp430/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/Common" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/SPP_drv/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/BLE_drv/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/SYS" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/SPP_drv/example app" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/BLE_drv/example app" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/SYS/MSP430Ware" --include_path="c:/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --advice:power=all -g --relaxed_ansi --define=__MSP430F5328__ --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="SYS/CYC_SYS_PWM.pp" --obj_directory="SYS" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SYS/CYC_SYS_Reset.obj: ../SYS/CYC_SYS_Reset.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"c:/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --preinclude="C:/ti/ccsv6/ccs_base/msp430/include/msp430f5xx_6xxgeneric.h" --include_path="c:/ti/ccsv6/ccs_base/msp430/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/Common" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/SPP_drv/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/BLE_drv/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/SYS" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/SPP_drv/example app" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/BLE_drv/example app" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/SYS/MSP430Ware" --include_path="c:/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --advice:power=all -g --relaxed_ansi --define=__MSP430F5328__ --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="SYS/CYC_SYS_Reset.pp" --obj_directory="SYS" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SYS/CYC_SYS_Timer.obj: ../SYS/CYC_SYS_Timer.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"c:/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --preinclude="C:/ti/ccsv6/ccs_base/msp430/include/msp430f5xx_6xxgeneric.h" --include_path="c:/ti/ccsv6/ccs_base/msp430/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/Common" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/SPP_drv/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/BLE_drv/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/SYS" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/SPP_drv/example app" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/BLE_drv/example app" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/SYS/MSP430Ware" --include_path="c:/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --advice:power=all -g --relaxed_ansi --define=__MSP430F5328__ --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="SYS/CYC_SYS_Timer.pp" --obj_directory="SYS" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SYS/CYC_SYS_UART.obj: ../SYS/CYC_SYS_UART.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"c:/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --preinclude="C:/ti/ccsv6/ccs_base/msp430/include/msp430f5xx_6xxgeneric.h" --include_path="c:/ti/ccsv6/ccs_base/msp430/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/Common" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/SPP_drv/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/BLE_drv/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/SYS" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/SPP_drv/example app" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/BLE_drv/example app" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/SYS/MSP430Ware" --include_path="c:/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --advice:power=all -g --relaxed_ansi --define=__MSP430F5328__ --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="SYS/CYC_SYS_UART.pp" --obj_directory="SYS" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SYS/msp430_interrupt.obj: ../SYS/msp430_interrupt.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"c:/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --preinclude="C:/ti/ccsv6/ccs_base/msp430/include/msp430f5xx_6xxgeneric.h" --include_path="c:/ti/ccsv6/ccs_base/msp430/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/Common" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/SPP_drv/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/BLE_drv/include" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/SYS" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/SPP_drv/example app" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/driver development/bluetooth files/BLE_drv/example app" --include_path="D:/work projects/Seebright/Firmware and Tools/Demo_KEY_LED_BLE/SYS/MSP430Ware" --include_path="c:/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --advice:power=all -g --relaxed_ansi --define=__MSP430F5328__ --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="SYS/msp430_interrupt.pp" --obj_directory="SYS" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


